export const CHARACTER_TRAITS = [
  "Brave",
  "Curious",
  "Kind",
  "Determined",
  "Mysterious",
  "Creative",
  "Witty",
  "Resourceful",
  "Loyal",
  "Ambitious",
  "Compassionate",
  "Eccentric",
  "Resilient",
  "Charismatic",
  "Wise",
  "Adventurous",
  "Cautious",
  "Optimistic",
  "Rebellious",
  "Patient",
  "Intuitive",
];

export const STORY_THEMES = [
  "Adventure",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Western",
  "Mythology",
  "Time Travel",
  "Supernatural",
  "Horror",
  "Coming of Age",
  "Fairy Tale",
];

export const STORY_MORALS = [
  "Be kind to others",
  "Never give up",
  "Tell the truth",
  "Help those in need",
  "Face your fears",
  "Work together",
  "Be yourself",
  "Think before you act",
  "Take responsibility",
  "Respect nature",
  "Value friendship",
  "Learn from mistakes",
];

export const IMAGE_STYLES = [
  "Watercolor",
  "Realistic",
  "Cartoon",
  "Pixel art",
  "Pencil",
  "Anime",
];
